apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: istio-io
  namespace: gcsweb
spec:
  secretName: istio-io-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - velodrome.istio.io
    - gcsweb.istio.io
  acme:
    config:
    - dns01:
        provider: clouddns
      domains:
        - gcsweb.istio.io
        - velodrome.istio.io
