apiVersion: v1
kind: Service
metadata:
  name: istio-io
  annotations:
    service.beta.kubernetes.io/external-traffic: OnlyLocal
spec:
  selector:
    app: istio-io
  type: LoadBalancer
  loadBalancerIP: 35.185.199.142
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
