# basic config options.
http-cache-dir: /cache/httpcache
organization: istio
project: istio
pr-mungers: lgtm-after-commit,submit-queue,needs-rebase,release-note-label,approval-handler
state: open
token-file: /etc/secret-volume/token
period: 1m
repo-dir: /gitrepos
github-key-file: /etc/hook-secret-volume/secret

# status context options.
required-contexts: "\
  prow/istio-presubmit.sh,\
  prow/e2e-suite-rbac-auth.sh"
protected-branches-extra-contexts: ""
required-retest-contexts: "\
  prow/istio-presubmit.sh,\
  prow/e2e-suite-rbac-auth.sh"

# submit-queue options.
protected-branches: ""
nonblocking-jenkins-jobs: ""
do-not-merge-milestones: ""
admin-port: "9999"
prow-url: "https://prow.istio.io"
context-url: ""
merge-method: "squash"

# Temporary gate approval process
gate-cla: true
gate-approved: true
