common_jobs_mods: &common_jobs_mods
  mapping:
    istio: istio-private
  input: ./prow/cluster/jobs/
  output: ./prow/cluster/jobs/
  branches: [release-1.4]
  repo-whitelist: [istio]
  ssh-clone: true
  extra-refs: true
  cluster: private
  modifier: priv
  annotations:
    testgrid-create-test-group: "false"
  verbose: false


transforms:

# istio/istio master build job(s) - postsubmit(s)
- <<: *common_jobs_mods
  env:
    DOCKER_HUB: gcr.io/istio-prow-build
    GCS_BUCKET: istio-private-build/dev
  labels:
    preset-enable-ssh: "true"
    preset-override-deps: release-1.4-istio
  job-type: [postsubmit]
  job-whitelist: [release_istio_release-1.4_postsubmit]

# istio/istio master test jobs(s) - presubmit(s) and postsubmit(s)
- <<: *common_jobs_mods
  labels:
    preset-enable-ssh: "true"
    preset-override-envoy: "true"
    preset-override-deps: release-1.4-istio
  job-type: [presubmit, postsubmit]
  job-blacklist: [release_istio_release-1.4_postsubmit]
