common_jobs_mods: &common_jobs_mods
  mapping:
    istio: istio-private
  input: ./prow/cluster/jobs/
  output: ./prow/cluster/jobs/
  branches: [master]
  repo-whitelist: [proxy]
  ssh-clone: true
  extra-refs: true
  cluster: private
  modifier: master_priv
  annotations:
    testgrid-create-test-group: "false"
  verbose: false


transforms:

# istio/proxy master test jobs(s) - presubmit(s)
- <<: *common_jobs_mods
  env:
    BAZEL_BUILD_RBE_INSTANCE: projects/istio-prow-build/instances/default_instance
    ENVOY_REPOSITORY: https://github.com/envoyproxy/envoy-wasm
    ENVOY_PREFIX: envoy-wasm
  labels:
    preset-enable-netrc: "true"
  job-type: [presubmit]

# istio/proxy master build jobs(s) - postsubmit(s)
- <<: *common_jobs_mods
  env:
    BAZEL_BUILD_RBE_INSTANCE: projects/istio-prow-build/instances/default_instance
    GCS_BUILD_BUCKET: istio-private-build
    GCS_ARTIFACTS_BUCKET: istio-private-artifacts
    DOCKER_REPOSITORY: istio-prow-build/envoy
    ENVOY_REPOSITORY: https://github.com/envoyproxy/envoy-wasm
    ENVOY_PREFIX: envoy-wasm
  labels:
    preset-enable-netrc: "true"
  job-type: [postsubmit]
