common_jobs_mods: &common_jobs_mods
  mapping:
    istio: istio-private
  input: ./prow/cluster/jobs/
  output: ./prow/cluster/jobs/
  branches: [release-1.4]
  ssh-clone: true
  extra-refs: true
  cluster: private
  modifier: priv
  annotations:
    testgrid-create-test-group: "false"
  verbose: false


transforms:

# istio/release-builder release-1.4 test jobs(s) - pre/postsubmit(s)
- <<: *common_jobs_mods
  job-type: [presubmit, postsubmit]
  repo-whitelist: [release-builder]
  job-whitelist: [lint_release-builder_release-1.4,lint_release-builder_release-1.4_postsubmit,test_release-builder_release-1.4,test_release-builder_release-1.4_postsubmit,gencheck_release-builder_release-1.4,gencheck_release-builder_release-1.4_postsubmit]

# istio/release-builder release-1.4 build warning jobs(s) - presubmit(s)
- <<: *common_jobs_mods
  env:
    PRERELEASE_DOCKER_HUB: gcr.io/istio-prow-build
    GCS_BUCKET: istio-private-prerelease/prerelease
  job-type: [presubmit]
  repo-whitelist: [release-builder]
  job-whitelist: [build-warning_release-builder_release-1.4]

  # istio/release-builder release-1.4 build jobs(s) - postsubmit(s)
- <<: *common_jobs_mods
  env:
    PRERELEASE_DOCKER_HUB: gcr.io/istio-prow-build
    GCS_BUCKET: istio-private-prerelease/prerelease
  labels:
    preset-enable-ssh: "true"
    preset-override-envoy: "true"
    preset-override-deps: release-1.4-release
  job-type: [postsubmit]
  repo-whitelist: [release-builder]
  job-whitelist: [build-release_release-builder_release-1.4_postsubmit]
