apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: branchprotector
spec:
  schedule: "*/30 * * * *"  # Run every 30 mn
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: branchprotector
    spec:
      template:
        spec:
          containers:
          - name: branchprotector
            image: gcr.io/istio-testing/branchprotector:v20180924-d9dc6563f
            args:
            - --config-path=/etc/config/config.yaml
            - --github-token-path=/etc/github/oauth
            - --job-config-path=/etc/job-config
            - --confirm
            volumeMounts:
            - name: oauth
              mountPath: /etc/github
              readOnly: true
            - name: config
              mountPath: /etc/config
              readOnly: true
            - name: job-config
              mountPath: /etc/job-config
              readOnly: true
          restartPolicy: Never
          volumes:
          - name: oauth
            secret:
              secretName: oauth-token
          - name: config
            configMap:
              name: config
          - name: job-config
            configMap:
              name: job-config
          nodeSelector:
            prod: prow
