---
kind: ServiceAccount
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/part-of: prow
  name: "crier"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/part-of: prow
  name: crier
rules:
- apiGroups:
  - "prow.k8s.io"
  resources:
  - "prowjobs"
  verbs:
  - "get"
  - "watch"
  - "list"
  - "patch"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  labels:
    app.kubernetes.io/part-of: prow
  name: "crier"
  namespace: "default"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "crier"
subjects:
- kind: ServiceAccount
  name: "crier"
  namespace: "default"
