apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/part-of: prow
  name: deck-private
spec:
  selector:
    app: deck-private
  ports:
  - port: 80
    targetPort: 4180
  type: NodePort
