---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/service-account.name: keel
  name: keel
  namespace: kube-system
  labels:
      name: "keel"
spec:
  replicas: 1
  template:
    metadata:
      name: keel
      labels:
        app: keel
    spec:
      containers:
        - image: costinm/keel:alpha
          imagePullPolicy: Always
          env:
            - name: NOTIFICATION_LEVEL
              value: "debug"
            - name: POLL
              value: "1"
            - name: PUBSUB
              value: "1"
            - name: PROJECT_ID
              value: "istio-testing"
            - name: GCLOUD_KEY_FILE
              value: "/var/keel/keel-secret.json"
            - name: "GOOGLE_APPLICATION_CREDENTIALS"
              value: "/var/keel/keel-secret.json"
          name: keel
          command: ["/bin/keel"]
          volumeMounts:
          - mountPath: /var/keel
            name: keel-secret
          ports:
            - containerPort: 9300
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9300
            initialDelaySeconds: 30
            timeoutSeconds: 10
      volumes:
      - name: keel-secret
        secret:
          optional: true
          secretName: keel-secret
