# basic config options.
http-cache-dir: /cache/httpcache
organization: istio
project: test-infra
pr-mungers: lgtm-after-commit,submit-queue,needs-rebase
state: open
token-file: /etc/secret-volume/token
period: 30s
repo-dir: /gitrepos
github-key-file: /etc/hook-secret-volume/secret

# status context options.
required-contexts: "prow/test-infra-presubmit.sh"
protected-branches-extra-contexts: ""
required-retest-contexts: "prow/test-infra-presubmit.sh"

# submit-queue options.
protected-branches: ""
nonblocking-jenkins-jobs: ""
do-not-merge-milestones: ""
admin-port: "9999"
prow-url: "https://prow.istio.io"
context-url: "http://104.196.250.254:8080"
merge-method: "squash"

# Temporary gate approval process
gate-cla: true
gate-approved: true

# Acceptable CLA label(s)
cla-yes-labels: "cla: yes,cla: human-approved"

blocking-labels: "do-not-merge/post-submit"
