# basic config options.
http-cache-dir: /cache/httpcache
organization: istio
project: test-infra
pr-mungers: lgtm-after-commit,submit-queue,needs-rebase,release-note-label,approval-handler
state: open
token-file: /etc/secret-volume/token
period: 1m
repo-dir: /gitrepos
github-key-file: /etc/hook-secret-volume/secret

# status context options.
required-contexts: "prow/test-infra-presubmit.sh"
protected-branches-extra-contexts: ""
required-retest-contexts: "prow/test-infra-presubmit.sh"

# submit-queue options.
protected-branches: ""
nonblocking-jenkins-jobs: ""
do-not-merge-milestones: ""
admin-port: "9999"
context-url: ""
merge-method: "squash"

# Temporary gate approval process
gate-cla: true
gate-approved: true
