---
apiVersion: v1
data:
  token: "@@"
kind: Secret
metadata:
  labels:
    app: submit-queue
    target-repo: test-infra
  name: test-infra-github-token
type: Opaque
---
apiVersion: v1
data:
  secret: "@@"
kind: Secret
metadata:
  labels:
    app: submit-queue
    target-repo: test-infra
  name: test-infra-github-secret
type: Opaque
