apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/part-of: gcsweb
  name: gcsweb
  namespace: gcs
spec:
  type: NodePort
  selector:
    app: gcsweb
  ports:
  - port: 80
    targetPort: 8080
