apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/part-of: boskos
  name: boskos
  namespace: boskos
spec:
  selector:
    app: boskos
  ports:
  - name: default
    protocol: TCP
    port: 80
    targetPort: 8080
