branches:
- release-1.5
image: gcr.io/istio-testing/build-tools:master-2020-01-18T00-45-13

jobs:
- command:
  - make
  - presubmit
  name: build
- command:
  - make
  - gen-check
  modifiers:
  - optional
  name: gencheck
org: istio
repo: api
resources:
  default:
    limits:
      cpu: "3"
      memory: 24Gi
    requests:
      cpu: 500m
      memory: 3Gi
