org: istio
repo: api
support_release_branching: true
image: gcr.io/istio-testing/build-tools:master-2020-01-28T02-27-49

jobs:
  - name: build
    command: [make, presubmit]

  - name: gencheck
    command: [make, gen-check]

  - name: gen_client-go
    type: postsubmit
    command:
    - ../test-infra/tools/automator/automator.sh
    - --org=istio
    - --repo=client-go
    - "--title=Automator: update istio/api@$AUTOMATOR_BRANCH dependency in $AUTOMATOR_ORG/$AUTOMATOR_REPO@$AUTOMATOR_BRANCH"
    - --modifier=client-go_update_api
    - --token-path=/etc/github-token/oauth
    - --cmd=go get istio.io/api@$AUTOMATOR_BRANCH && go mod tidy && make gen
    requirements: [github]
    repos: [istio/test-infra]

  - name: gen_istio
    type: postsubmit
    command:
    - ../test-infra/tools/automator/automator.sh
    - --org=istio
    - --repo=istio
    - "--title=Automator: update istio/api@$AUTOMATOR_BRANCH dependency in $AUTOMATOR_ORG/$AUTOMATOR_REPO@$AUTOMATOR_BRANCH"
    - --modifier=istio_update_api
    - --token-path=/etc/github-token/oauth
    - --cmd=go get istio.io/api@$AUTOMATOR_BRANCH && go mod tidy && make gen
    requirements: [github]
    repos: [istio/test-infra]
