org: istio
repo: api
support_release_branching: true
image: gcr.io/istio-testing/build-tools:master-2019-12-15T16-17-48

jobs:
  - name: build
    command: [make, presubmit]

  - name: gencheck
    command: [make, gen-check]

  - name: gen_client-go
    type: postsubmit
    command:
    - ../test-infra/tools/automator/automator.sh
    - --org=istio
    - --repo=client-go
    - --token-path=/etc/github-token/oauth
    - --cmd=go get istio.io/api@$AUTOMATOR_BRANCH && go mod tidy && make gen
    requirements: [github]
    repos: [istio/test-infra]

  - name: gen_istio
    type: postsubmit
    command:
    - ../test-infra/tools/automator/automator.sh
    - --org=istio
    - --repo=istio
    - --token-path=/etc/github-token/oauth
    - --cmd=go get istio.io/api@$AUTOMATOR_BRANCH && go mod tidy && make gen
    requirements: [github]
    repos: [istio/test-infra]
