org: istio
repo: api
support_release_branching: true
image: gcr.io/istio-testing/build-tools:master-2019-11-08T17-21-18

jobs:
  - name: build
    command: [make, presubmit]

  - name: gencheck
    command: [make, gen-check]
