org: istio
repo: client-go
support_release_branching: true
image: gcr.io/istio-testing/build-tools:master-2020-08-04T18-34-10

jobs:
  - name: build
    command: [make, build]

  - name: lint
    command: [make, lint]

  - name: gencheck
    command: [make, gen-check]
