org: istio
repo: client-go
image: gcr.io/istio-testing/build-tools:2019-08-31T04-48-30
suppress_entrypoint: true
branches:
  - master
  - release-1.3

jobs:
  - name: client-go-build
    command: [make, build]
  - name: client-go-lint
    command: [make, lint]
  - name: client-go-test
    command: [make, test]

resources:
  default:
    requests:
      memory: "3Gi"
      cpu: "500m"
    limits:
      memory: "24Gi"
      cpu: "3000m"