org: istio
repo: client-go
support_release_branching: true
image: gcr.io/istio-testing/build-tools:master-2019-12-15T16-17-48

jobs:
  - name: build
    command: [make, build]

  - name: lint
    command: [make, lint]

  - name: gencheck
    command: [make, gen-check]
