branches:
- release-1.5
image: gcr.io/istio-testing/build-tools:release-1.5-2020-03-24T16-54-03
jobs:
- command:
  - entrypoint
  - make
  - docker
  name: build
- command:
  - entrypoint
  - make
  - docker
  - test
  name: install
- command:
  - make
  - lint
  name: lint
- command:
  - make
  - gen-check
  name: gencheck
org: istio
repo: cni
resources:
  default:
    limits:
      cpu: "3"
      memory: 24Gi
    requests:
      cpu: 500m
      memory: 3Gi
