org: istio
repo: cni
branches:
  - master
  - release-1.3

jobs:
  - name: build
    command: [make, docker]
  - name: shellcheck
    command: [bin/check_shell_scripts.sh]
  - name: lint
    command: [make, lint]
  - name: install
    command: [make, docker, test]
  - name: e2e
    command: [make, prow-e2e]
    requirements: [kind]
    repos: [istio/istio]
