org: istio
repo: cni
branches:
  - master
  - release-1.3

jobs:
  - name: cni-build
    command: [make, docker]
  - name: cni-shellcheck
    command: [bin/check_shell_scripts.sh]
  - name: cni-lint
    command: [make, lint]
  - name: cni-install
    command: [make, docker, test]
  - name: cni-e2e
    command: [make, prow-e2e]
    requirements: [kind]
    repos: [istio/istio]
