org: istio
repo: cni
branches:
  - master
  - release-1.3

jobs:
  - name: build
    command: [make, docker]
  - name: lint
    command: [make, lint]
  - name: install
    command: [make, docker, test]
  - name: e2e
    command: [make, prow-e2e]
    requirements: [kind]
    repos: [istio/istio]

  - name: buildmodern
    command: [make, docker]
    image: gcr.io/istio-testing/build-tools:2019-08-31T04-48-30
    suppress_entrypoint: true
    modifiers: [optional]

  - name: lintmodern
    command: [make, lint_modern]
    image: gcr.io/istio-testing/build-tools:2019-08-31T04-48-30
    suppress_entrypoint: true
    modifiers: [optional]
