org: istio
repo: common-files
support_release_branching: true
image: gcr.io/istio-testing/build-tools:master-2020-02-14T13-09-14

jobs:
  - name: lint
    command: [make, lint]

  - name: update-common
    type: postsubmit
    command:
    - ../test-infra/tools/automator/automator.sh
    - --org=istio
    - --repo=istio,istio.io,api,test-infra,tools,bots,release-builder,pkg,cni,cri,client-go,gogo-genproto
    - "--title=Automator: update common-files@$AUTOMATOR_BRANCH in $AUTOMATOR_ORG/$AUTOMATOR_REPO@$AUTOMATOR_BRANCH"
    - --modifier=commonfiles
    - --token-path=/etc/github-token/oauth
    - --cmd=make update-common gen
    requirements: [github]
    repos: [istio/test-infra]

  - name: update-common-proxy
    image: gcr.io/istio-testing/build-tools-proxy:master-2020-02-14T13-09-14
    type: postsubmit
    command:
    - ../test-infra/tools/automator/automator.sh
    - --org=istio
    - --repo=proxy
    - "--title=Automator: update common-files@$AUTOMATOR_BRANCH in $AUTOMATOR_ORG/$AUTOMATOR_REPO@$AUTOMATOR_BRANCH"
    - --modifier=commonfiles-proxy
    - --token-path=/etc/github-token/oauth
    - --cmd=make update-common
    requirements: [github]
    repos: [istio/test-infra]