org: istio
repo: common-files
image: gcr.io/istio-testing/build-tools:2019-08-31T04-48-30
suppress_entrypoint: true
branches:
  - master
  - release-1.3

jobs:
  - name: common-files-lint
    command: [make, lint]
