org: istio
repo: community
image: gcr.io/istio-testing/build-tools:master-2021-07-01T20-30-56

jobs:
  - name: lint
    command: [prow/community-lint.sh]

  - name: test
    command: [make, test]

  - name: sync-org
    types: [postsubmit]
    command: [sh, prow/sync-org.sh]
    requirements: [github]
