org: istio
repo: community
image: gcr.io/istio-testing/build-tools:master-2020-03-11T15-35-42

jobs:
  - name: lint
    command: [prow/community-lint.sh]

  - name: test
    command: [make, test]

  - name: sync-org
    image: gcr.io/k8s-prow/peribolos:v20200311-9d5dcfe00
    type: postsubmit
    command:
    - /app/prow/cmd/peribolos/app.binary
    - --fix-org
    - --fix-org-members
    - --fix-teams
    - --fix-team-members
    - --config-path
    - org/istio.yaml
    - --github-token-path
    - /etc/github-token/oauth
    - --confirm
    requirements: [github]
