org: istio
repo: cri
image: gcr.io/istio-testing/build-tools:master-2019-12-03T17-07-58

jobs:
  - name: build
    command: [make, build]

  - name: lint
    command: [make, lint]

  - name: test
    command: [make, test]

  - name: gencheck
    command: [make, gen-check]
