org: istio
repo: cri
image: gcr.io/istio-testing/build-tools:master-2020-03-11T15-35-42

jobs:
  - name: build
    command: [make, build]

  - name: lint
    command: [make, lint]

  - name: test
    command: [make, test]

  - name: gencheck
    command: [make, gen-check]
