org: istio
repo: envoy
branches: [release-1.7]
image: envoyproxy/envoy-build-ubuntu:f21773ab398a879f976936f72c78c9dd3718ca1e
node_selector:
  testing: build-pool

jobs:
- name: test-asan
  type: presubmit
  env:
  - name: BAZEL_BUILD_EXTRA_OPTIONS
    value: "--local_ram_resources=131072 --local_cpu_resources=42 --test_env=ENVOY_IP_TEST_VERSIONS=v4only --flaky_test_attempts=9"
  - name: ENVOY_SRCDIR
    value: "/home/prow/go/src/istio.io/envoy"
  command: [./ci/do_ci.sh, bazel.asan]

- name: test-tsan
  type: presubmit
  env:
  - name: BAZEL_BUILD_EXTRA_OPTIONS
    value: "--local_ram_resources=131072 --local_cpu_resources=42 --test_env=ENVOY_IP_TEST_VERSIONS=v4only --flaky_test_attempts=9"
  - name: ENVOY_SRCDIR
    value: "/home/prow/go/src/istio.io/envoy"
  command: [./ci/do_ci.sh, bazel.tsan]

- name: test-release
  type: presubmit
  env:
  - name: BAZEL_BUILD_EXTRA_OPTIONS
    value: "--local_ram_resources=131072 --local_cpu_resources=42 --test_env=ENVOY_IP_TEST_VERSIONS=v4only --flaky_test_attempts=9"
  - name: ENVOY_SRCDIR
    value: "/home/prow/go/src/istio.io/envoy"
  command: [./ci/do_ci.sh, bazel.release]

- name: update-proxy
  type: postsubmit
  command:
  - ../test-infra/tools/automator/automator.sh
  - --org=istio
  - --repo=proxy
  - "--title=Automator: update envoy@$AUTOMATOR_SRC_BRANCH in $AUTOMATOR_ORG/$AUTOMATOR_REPO@$AUTOMATOR_BRANCH"
  - --labels=auto-merge,release-notes-none
  - --modifier=update_envoy_dep
  - --token-path=/etc/github-token/oauth
  - --cmd=scripts/update_envoy.sh $AUTOMATOR_SHA $AUTOMATOR_SHA_COMMIT_DATE
  requirements: [github]
  repos: [istio/test-infra@master]
  image: gcr.io/istio-testing/build-tools:master-2020-09-15T14-05-50
  timeout: 4h

resources:
  default:
    requests:
      memory: "180G"
      cpu: "48"
      ephemeral-storage: "1500G"
    limits:
      memory: "240G"
      cpu: "64"
      ephemeral-storage: "1790G"
