org: istio
repo: gogo-genproto
image: gcr.io/istio-testing/build-tools:2019-08-31T04-48-30
suppress_entrypoint: true
branches:
  - master
  - release-1.3

jobs:
  - name: gogo-genproto-build
    command: [make, build]
  - name: gogo-genproto-lint
    command: [make, lint]
