org: istio
repo: gogo-genproto
support_release_branching: true
image: gcr.io/istio-testing/build-tools:master-2020-03-04T04-41-33

jobs:
  - name: build
    command: [make, build]

  - name: lint
    command: [make, lint]

  - name: gencheck
    command: [make, gen-check]
