org: istio
repo: installer
image: gcr.io/istio-testing/build-tools:2019-08-31T04-48-30
suppress_entrypoint: true
branches:
  - master

jobs:
  - name: build
    command: [make, run-build]
    modifier: optional
