org: istio
repo: istio
support_release_branching: true
image: gcr.io/istio-testing/build-tools:master-2020-01-28T02-27-49

jobs:
  - name: unit-tests
    command: [entrypoint, make, -e, "T=-v", build, localTestEnv, racetest, binaries-test]

  - name: codecov
    modifiers: [skipped]
    command: [entrypoint, make, coverage-diff]

  - name: release-test
    type: presubmit
    command: [entrypoint, prow/release-test.sh]
    requirements: [gcp]

  - name: release
    type: postsubmit
    command: [entrypoint, prow/release-commit.sh]
    requirements: [gcp]

  - name: integ-galley-local-tests
    type: presubmit
    command: [entrypoint, prow/integ-suite-local.sh, test.integration.galley.local.presubmit]
    requirements: [docker]

  - name: integ-pilot-local-tests
    type: presubmit
    command: [entrypoint, prow/integ-suite-local.sh, test.integration.pilot.local.presubmit]
    requirements: [docker]

  - name: integ-security-local-tests
    type: presubmit
    command: [entrypoint, prow/integ-suite-local.sh, test.integration.security.local.presubmit]
    requirements: [docker]

  - name: integ-conformance-local-tests
    type: presubmit
    command: [entrypoint, prow/integ-suite-local.sh, test.integration.conformance.local.presubmit]
    requirements: [docker]

  - name: integ-galley-k8s-tests
    type: presubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.galley.kube.presubmit]
    requirements: [kind]
    env:
    - name: TEST_USE_OPERATOR
      value: "true"

  - name: integ-mixer-k8s-tests
    type: presubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.mixer.kube.presubmit]
    requirements: [kind]
    modifiers: [optional]
    env:
    - name: TEST_USE_OPERATOR
      value: "true"

  - name: integ-pilot-k8s-tests
    type: presubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.pilot.kube.presubmit]
    requirements: [kind]
    env:
    - name: TEST_USE_OPERATOR
      value: "true"

  - name: integ-security-k8s-tests
    type: presubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.security.kube.presubmit]
    requirements: [kind]
    env:
    - name: TEST_USE_OPERATOR
      value: "true"

  - name: integ-telemetry-k8s-tests
    type: presubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.telemetry.kube.presubmit]
    requirements: [kind]
    env:
    - name: TEST_USE_OPERATOR
      value: "true"

  - name: integ-istioio-k8s-tests
    type: presubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.istioio.kube.presubmit]
    requirements: [kind]
    modifiers: [optional]

  - name: integ-istioio-k8s-tests
    type: postsubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.istioio.kube.postsubmit]
    requirements: [kind, gcp]
    modifiers: [optional]

  - name: integ-distroless-k8s-tests
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.kube.reachability]
    requirements: [kind]
    env:
    - name: VARIANT
      value: "distroless"

  - name: integ-conformance-k8s-tests
    type: presubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.conformance.kube.presubmit]
    requirements: [kind]

  - name: e2e-mixer-no_auth
    command: [entrypoint, prow/e2e-kind-suite.sh, --single_test, e2e_mixer]
    requirements: [kind]

  - name: pilot-e2e-envoyv2-v1alpha3
    command: [entrypoint, prow/e2e-kind-suite.sh, --single_test, e2e_pilotv2_v1alpha3]
    requirements: [kind]

  - name: e2e-dashboard
    command: [entrypoint, prow/e2e-kind-suite.sh, --single_test, e2e_dashboard]
    requirements: [kind]

  - name: e2e-bookInfoTests-envoyv2-v1alpha3
    command: [entrypoint, prow/e2e-kind-suite.sh, --single_test, e2e_bookinfo_envoyv2_v1alpha3]
    requirements: [kind]

  - name: e2e-bookInfoTests-trustdomain
    command: [entrypoint, prow/e2e-kind-suite.sh, --single_test, e2e_bookinfo_trustdomain]
    requirements: [kind]
    type: postsubmit

  - name: e2e-bookInfoTests-non-mcp
    type: postsubmit
    command: [entrypoint, prow/e2e-kind-suite.sh, --use_mcp=false, --single_test, e2e_bookinfo_envoyv2_v1alpha3]
    requirements: [kind]

  - name: pilot-multicluster-e2e
    command: [entrypoint, prow/istio-pilot-multicluster-e2e.sh]
    requirements: [kind]

  - name: integ-galley-local-tests
    type: postsubmit
    command: [entrypoint, prow/integ-suite-local.sh, test.integration.galley.local]
    requirements: [docker]

  - name: integ-pilot-local-tests
    type: postsubmit
    command: [entrypoint, prow/integ-suite-local.sh, test.integration.pilot.local]
    requirements: [docker]

  - name: integ-security-local-tests
    type: postsubmit
    command: [entrypoint, prow/integ-suite-local.sh, test.integration.security.local]
    requirements: [docker]

  - name: integ-conformance-local-tests
    type: postsubmit
    command: [entrypoint, prow/integ-suite-local.sh, test.integration.conformance.local]
    requirements: [docker]

  - name: integ-galley-k8s-tests
    type: postsubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.galley.kube]
    requirements: [kind]
    env:
    - name: TEST_USE_OPERATOR
      value: "true"

  - name: integ-mixer-k8s-tests
    type: postsubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.mixer.kube]
    requirements: [kind]
    env:
    - name: TEST_USE_OPERATOR
      value: "true"

  - name: integ-pilot-k8s-tests
    type: postsubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.pilot.kube]
    requirements: [kind]
    env:
    - name: TEST_USE_OPERATOR
      value: "true"

  - name: integ-security-k8s-tests
    type: postsubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.security.kube]
    requirements: [kind]
    env:
    - name: TEST_USE_OPERATOR
      value: "true"

  - name: integ-telemetry-k8s-tests
    type: postsubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.telemetry.kube]
    requirements: [kind]
    env:
    - name: TEST_USE_OPERATOR
      value: "true"

  - name: integ-conformance-k8s-tests
    type: postsubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.conformance.kube]
    requirements: [kind]

    # The node image must be kept in sync with the kind version we use.
    # See docker/istio/shared/tools/install-golang.sh for the kind image
    # https://github.com/kubernetes-sigs/kind/releases for node corresponding node image
  - name: integ-k8s-114
    type: postsubmit
    command:
      - entrypoint
      - prow/integ-suite-kind.sh
      - --node-image
      - kindest/node:v1.14.9
      - test.integration.kube.presubmit
    requirements: [kind]
    timeout: 4h

  - name: integ-k8s-115
    type: postsubmit
    command:
      - entrypoint
      - prow/integ-suite-kind.sh
      - --node-image
      - kindest/node:v1.15.6
      - test.integration.kube.presubmit
    requirements: [kind]
    timeout: 4h

  - name: integ-k8s-116
    type: postsubmit
    command:
      - entrypoint
      - prow/integ-suite-kind.sh
      - --node-image
      - kindest/node:v1.16.3
      - test.integration.kube.presubmit
    requirements: [kind]
    timeout: 4h

  - name: lint
    command: [make, lint]
    resources: lint

  - name: gencheck
    command: [make, gen-check]

resources:
  default:
    requests:
      memory: "3Gi"
      cpu: "5000m"
    limits:
      memory: "24Gi"
      cpu: "8000m"
  lint:
    requests:
      memory: "16Gi"
      cpu: "3000m"
    limits:
      memory: "24Gi"
      cpu: "5000m"
