org: istio
repo: istio.io
support_release_branching: true
image: gcr.io/istio-testing/build-tools:master-2020-03-04T04-41-33

jobs:
  - name: lint
    command: [make, lint]

  - name: k8s-tests
    type: presubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.kube.presubmit]
    requirements: [kind]

  - name: k8s-tests
    type: postsubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.kube.postsubmit]
    requirements: [kind, gcp]

resources:
  default:
    requests:
      memory: "3Gi"
      cpu: "5000m"
    limits:
      memory: "24Gi"
      cpu: "8000m"
  lint:
    requests:
      memory: "16Gi"
      cpu: "3000m"
    limits:
      memory: "24Gi"
      cpu: "5000m"
