org: istio
repo: istio.io
image: gcr.io/istio-testing/build-tools:2019-08-31T04-48-30
suppress_entrypoint: true
branches:
  - master
  - release-1.2

jobs:
  - name: istio.io-lint
    command: [make, lint]
