org: istio
repo: operator
image: gcr.io/istio-testing/build-tools:2019-09-17T18-24-15
branches:
  - release-1.3

jobs:
  - name: lint
    command: [make, lint]

  - name: mesh
    command: [make, mesh]

  - name: test
    command: [make, test]

  - name: mandiff
    command: [make, mandiff]

  - name: manifest-apply
    image: gcr.io/istio-testing/istio-builder:v20191017-386873c9-dirty
    command: [entrypoint, prow/e2e_install.sh]
    requirements: [kind]
    modifiers: [optional, hidden]
