org: istio
repo: operator
support_release_branching: true
image:gcr.io/istio-testing/build-tools:master-2019-12-03T17-07-58

jobs:
  - name: lint
    command: [make, lint]

  - name: mesh
    command: [make, mesh]

  - name: test
    command: [make, test]

  - name: mandiff
    command: [make, mandiff]

  - name: gencheck
    command: [make, gen-check]

  - name: e2e
    command: [entrypoint, make, e2e]
    requirements: [kind]

  - name: release
    type: postsubmit
    command: [entrypoint, make, docker.all]
    requirements: [gcp]
