org: istio
repo: test-infra
image: gcr.io/istio-testing/build-tools:master-2019-12-15T16-17-48

jobs:
  - name: lint
    command: [make, lint]

  - name: test
    command: [make, test]

  - name: gencheck
    command: [make, gen-check]

  - name: push-authentikos
    type: postsubmit
    regex: '^authentikos/Makefile$'
    cluster: test-infra-trusted
    max_concurrency: 1
    command:
    - entrypoint
    - make
    - -C
    - authentios
    - deploy
    requirements:
    - docker

  - name: push-genjobs
    type: postsubmit
    regex: '^prow/genjobs/Makefile$'
    cluster: test-infra-trusted
    max_concurrency: 1
    command:
    - entrypoint
    - make
    - -C
    - prow/genjobs
    - deploy
    requirements:
    - docker
