org: istio
repo: test-infra
image: gcr.io/istio-testing/build-tools:master-2020-04-09T21-48-25

jobs:
  - name: lint
    command: [make, lint]

  - name: test
    command: [make, test]

  - name: gencheck
    command: [make, gen-check]

  - name: unit-test-authentikos
    type: presubmit
    # trigger on changes in `authentikos/` directory to the following:
    # - `.go`    : Golang source files. When the source code changes, test the validity of the change.
    # - `go.mod` : Golang module dependencies. When the dependencies change, test the compatibility of the change.
    regex: '^authentikos/(.+\.go|go\.mod)$'
    command: [make, -C, authentikos, unit-test]

  - name: integ-test-authentikos
    type: presubmit
    # trigger on changes in `authentikos/` directory to the following:
    # - `test/`  : integration test library, scripts, and object configuration files.
    #              If there are changes to the tests themselves, run the modified tests.
    # - `.go`    : Golang source files. When the source code changes, test the validity of the change.
    # - `go.mod` : Golang module dependencies. When the dependencies change, test the compatibility of the change.
    regex: '^authentikos/(test/.+|.+\.go|go\.mod)$'
    command: [entrypoint, make, -C, authentikos, integ-test]
    requirements: [kind, gcp]

  - name: deploy-prow
    type: postsubmit
    regex: '^prow/cluster/(?:gcsweb/|build/|private/|[^/]+\.yaml$)'
    cluster: test-infra-trusted
    max_concurrency: 1
    command:
    - make
    - -C
    - prow
    - deploy
    - deploy-gcsweb
    - deploy-velodrome
    - deploy-build
    - deploy-private
    requirements: [deploy]
    node_selector:
      prod: prow

  - name: deploy-boskos
    type: postsubmit
    regex: '^boskos/cluster/.*\.yaml$'
    cluster: test-infra-trusted
    max_concurrency: 1
    command:
    - make
    - -C
    - boskos
    - deploy
    requirements: [deploy]
    node_selector:
        prod: prow

  - name: deploy-boskos-config
    type: postsubmit
    regex: '^boskos/resources.yaml$'
    cluster: test-infra-trusted
    max_concurrency: 1
    command:
    - make
    - -C
    - boskos
    - boskos-config
    requirements: [deploy]
    node_selector:
        prod: prow

  - name: push-mason
    type: postsubmit
    regex: '^boskos/cmd/mason/.+'
    cluster: test-infra-trusted
    max_concurrency: 1
    command:
    - make
    - -C
    - boskos
    - mason-image
    requirements: [docker, gcp]
    node_selector:
        prod: prow

  - name: push-prowbazel
    type: postsubmit
    regex: '^docker/prowbazel/Makefile$'
    cluster: test-infra-trusted
    max_concurrency: 1
    command:
    - entrypoint
    - make
    - -C
    - docker/prowbazel
    - image
    - push-safe
    requirements: [docker, gcp]
    node_selector:
        prod: prow

  - name: push-authentikos
    type: postsubmit
    regex: '^authentikos/Makefile$'
    cluster: test-infra-trusted
    max_concurrency: 1
    command:
    - entrypoint
    - make
    - -C
    - authentikos
    - deploy
    requirements: [docker, gcp]
    node_selector:
      prod: prow

  - name: push-genjobs
    type: postsubmit
    regex: '^prow/genjobs/Makefile$'
    cluster: test-infra-trusted
    max_concurrency: 1
    command:
    - entrypoint
    - make
    - -C
    - prow/genjobs
    - deploy
    requirements: [docker, gcp]
    node_selector:
      prod: prow
