org: istio
repo: test-infra
image: gcr.io/istio-testing/build-tools:master-2020-03-05T18-27-04

jobs:
  - name: lint
    command: [make, lint]

  - name: test
    command: [make, test]

  - name: gencheck
    command: [make, gen-check]

  - name: deploy-prow
    type: postsubmit
    regex: '^prow/cluster/(?:gcsweb/|build/|private/|[^/]+\.yaml$)'
    cluster: test-infra-trusted
    max_concurrency: 1
    command:
    - make
    - -C
    - prow
    - deploy
    - deploy-gcsweb
    - deploy-build
    - deploy-private
    requirements: [deploy]
    node_selector:
      prod: prow

  - name: deploy-boskos
    type: postsubmit
    regex: '^boskos/cluster/.*\.yaml$'
    cluster: test-infra-trusted
    max_concurrency: 1
    command:
    - make
    - -C
    - boskos
    - deploy
    requirements: [deploy]
    node_selector:
        prod: prow

  - name: deploy-boskos-config
    type: postsubmit
    regex: '^boskos/resources.yaml$'
    cluster: test-infra-trusted
    max_concurrency: 1
    command:
    - make
    - -C
    - boskos
    - boskos-config
    requirements: [deploy]
    node_selector:
        prod: prow

  - name: push-mason
    type: postsubmit
    regex: '^boskos/cmd/mason/.+'
    cluster: test-infra-trusted
    max_concurrency: 1
    command:
    - make
    - -C
    - boskos
    - mason-image
    requirements: [docker, gcp]
    node_selector:
        prod: prow

  - name: push-prowbazel
    type: postsubmit
    regex: '^docker/prowbazel/Makefile$'
    cluster: test-infra-trusted
    max_concurrency: 1
    command:
    - entrypoint
    - make
    - -C
    - docker/prowbazel
    - image
    - push-safe
    requirements: [docker, gcp]
    node_selector:
        prod: prow

  - name: push-authentikos
    type: postsubmit
    regex: '^authentikos/Makefile$'
    cluster: test-infra-trusted
    max_concurrency: 1
    command:
    - entrypoint
    - make
    - -C
    - authentikos
    - deploy
    requirements: [docker, gcp]
    node_selector:
      prod: prow

  - name: push-genjobs
    type: postsubmit
    regex: '^prow/genjobs/Makefile$'
    cluster: test-infra-trusted
    max_concurrency: 1
    command:
    - entrypoint
    - make
    - -C
    - prow/genjobs
    - deploy
    requirements: [docker, gcp]
    node_selector:
      prod: prow
