org: istio
repo: test-infra
image: gcr.io/istio-testing/build-tools:master-2020-01-28T02-27-49

jobs:
  - name: lint
    command: [make, lint]

  - name: test
    command: [make, test]

  - name: gencheck
    command: [make, gen-check]

  - name: deploy-prow
    type: postsubmit
    regex: '^prow/cluster/(?:gcsweb/|build/|private/|[^/]+\.yaml$)'
    cluster: test-infra-trusted
    max_concurrency: 1
    command:
    - make
    - -C
    - prow
    - deploy
    - deploy-gcsweb
    - deploy-build
    - deploy-private
    requirements:
    - deploy
    node_selector:
      prod: prow

  - name: push-authentikos
    type: postsubmit
    regex: '^authentikos/Makefile$'
    cluster: test-infra-trusted
    max_concurrency: 1
    command:
    - entrypoint
    - make
    - -C
    - authentios
    - deploy
    requirements:
    - docker
    node_selector:
      prod: prow

  - name: push-genjobs
    type: postsubmit
    regex: '^prow/genjobs/Makefile$'
    cluster: test-infra-trusted
    max_concurrency: 1
    command:
    - entrypoint
    - make
    - -C
    - prow/genjobs
    - deploy
    requirements:
    - docker
    node_selector:
      prod: prow
