org: istio
repo: tools
image: gcr.io/istio-testing/build-tools:2019-09-17T18-24-15
suppress_entrypoint: true
branches:
  - master

jobs:
  - name: build
    command: [make, build]
  - name: lint
    command: [make, lint]
  - name: test
    command: [make, test]
