apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: submit-queue
    target-repo: test-infra
  name: mungegithub-test-infra-cache
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: mungegithub-test-infra-cache
    fsType: ext4
