apiVersion: apps/v1
kind: Deployment
metadata:
  name: boskos-cleaner
  labels:
    app: boskos-cleaner
  namespace: boskos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boskos-cleaner
  template:
    metadata:
      labels:
        app: boskos-cleaner
    spec:
      serviceAccountName: boskos-reader
      terminationGracePeriodSeconds: 300
      containers:
      - name: boskos-cleaner
        image: gcr.io/k8s-prow/boskos/cleaner:v20190730-dbac84bd7
        args:
        - --cleaner-count=3
        - --namespace=boskos

