configs:
- name: gke-e2e-test-latest
  needs:
    gcp-project: 1
  config:
    type: GCPResourceConfig
    content: |
      gcp-project:
        - clusters:
          - machinetype: n1-standard-2
            numnodes: 4
            version: 1.11
            networkpolicy:
              enabled: true
              provider: CALICO
          - machinetype: n1-standard-2
            numnodes: 4
            version: 1.11
            networkpolicy:
              enabled: true
              provider: CALICO
            scopes:
            - https://www.googleapis.com/auth/cloud-platform
            - https://www.googleapis.com/auth/trace.append
          vms:
          - machinetype: n1-standard-4
            sourceimage: projects/debian-cloud/global/images/debian-9-stretch-v20180206
            tags:
            - http-server
            - https-server
            scopes:
            - https://www.googleapis.com/auth/cloud-platform
            - https://www.googleapis.com/auth/trace.append
- name: gke-e2e-test
  needs:
    gcp-project: 1
  config:
    type: GCPResourceConfig
    content: |
      gcp-project:
        - clusters:
          - machinetype: n1-standard-4
            numnodes: 5
            version: 1.10
          - machinetype: n1-standard-4
            numnodes: 5
            version: 1.10
            scopes:
            - https://www.googleapis.com/auth/cloud-platform
            - https://www.googleapis.com/auth/trace.append
          vms:
          - machinetype: n1-standard-4
            sourceimage: projects/debian-cloud/global/images/debian-9-stretch-v20180206
            tags:
            - http-server
            - https-server
            scopes:
            - https://www.googleapis.com/auth/cloud-platform
            - https://www.googleapis.com/auth/trace.append

- name: gke-perf-preset
  needs:
    gcp-perf-test: 1
  config:
    type: GCPResourceConfig
    content: |
      gcp-perf-test:
        - clusters:
          - machinetype: n1-highmem-8
            numnodes: 7
            version: 1.10
            zone: us-central1-f
            scopes:
            - https://www.googleapis.com/auth/cloud-platform
            - https://www.googleapis.com/auth/trace.append
          vms:
          - machinetype: n1-highmem-8
            sourceimage: projects/ubuntu-os-cloud/global/images/ubuntu-1604-xenial-v20180612
            zone: us-central1-f
            tags:
            - http-server
            - https-server
            scopes:
            - https://www.googleapis.com/auth/cloud-platform
            - https://www.googleapis.com/auth/trace.append
