configs:
- name: gke-e2e-test-1-10
  needs:
    gcp-project: 1
  config:
    type: GCPResourceConfig
    content: |
      gcp-project:
        - clusters:
          - machinetype: n1-standard-2
            numnodes: 4
            version: 1.10
          - machinetype: n1-standard-2
            numnodes: 4
            version: 1.10
          vms:
          - machinetype: n1-standard-4
            sourceimage: projects/debian-cloud/global/images/debian-9-stretch-v20180206
            tags:
            - http-server
            - https-server
            scopes:
            - https://www.googleapis.com/auth/cloud-platform
- name: gke-e2e-test
  needs:
    gcp-project: 1
  config:
    type: GCPResourceConfig
    content: |
      gcp-project:
        - clusters:
          - machinetype: n1-standard-2
            numnodes: 4
            version: 1.9
          - machinetype: n1-standard-2
            numnodes: 4
            version: 1.9
          vms:
          - machinetype: n1-standard-4
            sourceimage: projects/debian-cloud/global/images/debian-9-stretch-v20180206
            tags:
            - http-server
            - https-server
            scopes:
            - https://www.googleapis.com/auth/cloud-platform

- name: gke-perf-preset
  needs:
    gcp-perf-test: 1
  config:
    type: GCPResourceConfig
    content: |
      gcp-perf-test:
        - clusters:
          - machinetype: n1-highcpu-2
            numnodes: 6
            version: 1.9
            zone: us-central1-f
          vms:
          - machinetype: n1-highcpu-2
            sourceimage: projects/ubuntu-os-cloud/global/images/ubuntu-1604-xenial-v20180323
            zone: us-central1-f
            tags:
            - http-server
            - https-server
            scopes:
            - https://www.googleapis.com/auth/cloud-platform
