apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: boskos-janitor
  labels:
    app: boskos-janitor
  namespace: boskos
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: boskos-janitor
    spec:
      terminationGracePeriodSeconds: 300
      containers:
      - name: boskos-janitor
        image: gcr.io/k8s-testimages/janitor:v20180531-fb2d8fcb9
        args:
        - --service-account=/etc/service-account/service-account.json
        - --resource-type=gcp-project,gcp-perf-test
        - --pool-size=20
        volumeMounts:
        - mountPath: /etc/service-account
          name: boskos-service-account
          readOnly: true
      volumes:
      - name: boskos-service-account
        secret:
          secretName: boskos-service-account
