apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: boskos-mason
  labels:
    app: boskos-mason
  namespace: boskos
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: boskos-mason
    spec:
      terminationGracePeriodSeconds: 300
      containers:
      - name: boskos-mason
        image: gcr.io/istio-testing/mason:v20190417-87a1e7f
        args:
        - --config=/etc/config/configs.yaml
        - --service-account=/etc/service-account/service-account.json
        - --cleaner-count=25
        volumeMounts:
        - mountPath: /etc/service-account
          name: service-account
          readOnly: true
        - mountPath: /etc/config
          name: config
          readOnly: true
      volumes:
      - name: service-account
        secret:
          secretName: boskos-service-account
      - name: config
        configMap:
          name: mason-config
      nodeSelector:
        prod: prow
