apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: boskos-reaper
  labels:
    app: boskos-reaper
  namespace: boskos
spec:
  replicas: 1  # one canonical source of resources
  template:
    metadata:
      labels:
        app: boskos-reaper
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: boskos-reaper
        image: gcr.io/k8s-testimages/reaper:v20180402-43203f868
        args:
        - --resource-type=gke-perf-preset,gcp-perf-test,gcp-project,gke-e2e-test,gke-e2e-test-1-10
      nodeSelector:
        prod: prow

