# basic config options.
http-cache-dir: /cache/httpcache
organization: istio
project: proxy
pr-mungers: submit-queue
state: open
token-file: /etc/secret-volume/token
period: 1m
repo-dir: /gitrepos
github-key-file: /etc/hook-secret-volume/secret

# status context options.
required-contexts: "\
  prow/proxy-presubmit.sh,\
  prow/proxy-presubmit-asan.sh,\
  prow/proxy-presubmit-tsan.sh"
protected-branches-extra-contexts: ""
required-retest-contexts: "\
  prow/proxy-presubmit.sh,\
  prow/proxy-presubmit-asan.sh,\
  prow/proxy-presubmit-tsan.sh"

# submit-queue options.
protected-branches: ""
nonblocking-jenkins-jobs: ""
do-not-merge-milestones: ""
admin-port: "9999"
prow-url: "https://prow.istio.io"
context-url: "http://35.197.99.161:8080"
merge-method: "squash"

# Temporary gate approval process
gate-cla: true
gate-approved: true

# Acceptable CLA label(s)
cla-yes-labels: "cla: yes,cla: human-approved"
