---
plank:
  job_url_template: 'https://k8s-gubernator.appspot.com/build/istio-prow/{{if eq .Spec.Type "presubmit"}}pull/{{.Spec.Refs.Org}}_{{.Spec.Refs.Repo}}/{{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}{{else}}.{{end}}/{{.Spec.Job}}/{{.Status.BuildID}}/'
  job_url_prefix: https://k8s-gubernator.appspot.com/build/
  pod_pending_timeout: 60m
  default_decoration_config:
    timeout: 7200000000000 # 2h
    grace_period: 15000000000 # 15s
    utility_images:
      clonerefs: "gcr.io/k8s-prow/clonerefs:v20181017-d31417a"
      initupload: "gcr.io/k8s-prow/initupload:v20181017-d31417a"
      entrypoint: "gcr.io/k8s-prow/entrypoint:v20181017-d31417a"
      sidecar: "gcr.io/k8s-prow/sidecar:v20181017-d31417a"
    gcs_configuration:
      bucket: "istio-prow"
      path_strategy: "explicit"
    gcs_credentials_secret: "service-account"

sinker:
  resync_period: 1h
  max_prowjob_age: 168h
  max_pod_age: 12h

deck:
  tide_update_period: 1s

prowjob_namespace: default
pod_namespace: test-pods

blocked_branches: &blocked_branches
  release-0.1: &blocking_merge
    required_status_checks:
      contexts:
      - "merges-blocked-needs-admin"
    protect: true
  release-0.2:
    <<: *blocking_merge
  release-0.3:
    <<: *blocking_merge
  release-0.3.0:
    <<: *blocking_merge
  release-0.4:
    <<: *blocking_merge
  release-0.4.0:
    <<: *blocking_merge
  release-0.5:
    <<: *blocking_merge
  release-0.6:
    <<: *blocking_merge
  release-0.7:
    <<: *blocking_merge
  release-0.8:
    <<: *blocking_merge
  release-1.0:
    <<: *blocking_merge

branch-protection:
  allow_disabled_policies: true
  orgs:
    istio:
      required_status_checks:
        contexts:
        - cla/google
      required_pull_request_reviews:
        required_approving_review_count: 1
      restrictions:
        teams:
        - repo-admins
      repos:
        api:
          protect: false
          branches:
            <<: *blocked_branches
            release-1.2:
              protect: true
              required_status_checks:
                contexts:
                - "merges-blocked-needs-admin"
            release-1.1:
              protect: true
              required_status_checks:
                contexts:
                - "merges-blocked-needs-admin"
            master:
              protect: true
        istio:
          protect: false
          required_status_checks:
            contexts:
            - "ci/circleci: build"
            - "ci/circleci: e2e-simple"
            - "ci/circleci: lint"
            - "ci/circleci: test"
          branches:
            <<: *blocked_branches
            collab-galley:
              protect: true
              restrictions:
                teams:
                - istio-hackers
            collab-gcp-identity:
              protect: true
              restrictions:
                teams:
                - istio-hackers
            release-1.1:
              protect: true
              required_status_checks:
                contexts:
                - "ci/circleci: codecov"
                - "ci/circleci: shellcheck"
                - "ci/circleci: e2e-galley"
                - "ci/circleci: e2e-pilot-auth-v1alpha3-v2"
                - "ci/circleci: e2e-pilot-noauth-v1alpha3-v2"
                - "ci/circleci: e2e-mixer-noauth-v1alpha3-v2"
                - "ci/circleci: e2e-pilot-cloudfoundry-v1alpha3-v2"
                - "merges-blocked-needs-admin"
            release-1.2:
              protect: true
              required_status_checks:
                contexts:
                - "ci/circleci: codecov"
                - "ci/circleci: shellcheck"
                - "ci/circleci: e2e-galley"
                - "ci/circleci: e2e-pilot-auth-v1alpha3-v2"
                - "ci/circleci: e2e-pilot-noauth-v1alpha3-v2"
                - "ci/circleci: e2e-mixer-noauth-v1alpha3-v2"
                - "ci/circleci: e2e-pilot-cloudfoundry-v1alpha3-v2"
                - "merges-blocked-needs-admin"
            authz-v2:
              protect: true
              required_status_checks:
                contexts:
                - "ci/circleci: codecov"
                - "ci/circleci: shellcheck"
                - "ci/circleci: e2e-galley"
                - "ci/circleci: e2e-pilot-auth-v1alpha3-v2"
                - "ci/circleci: e2e-pilot-noauth-v1alpha3-v2"
                - "ci/circleci: e2e-mixer-noauth-v1alpha3-v2"
                - "ci/circleci: e2e-pilot-cloudfoundry-v1alpha3-v2"
            master:
              protect: true
              required_status_checks:
                contexts:
                - "ci/circleci: codecov"
                - "ci/circleci: racetest"
                - "ci/circleci: shellcheck"
                - "ci/circleci: e2e-pilot-auth-v1alpha3-v2"
                - "ci/circleci: e2e-pilot-noauth-v1alpha3-v2"
                - "ci/circleci: e2e-mixer-noauth-v1alpha3-v2"
                - "ci/circleci: e2e-pilot-cloudfoundry-v1alpha3-v2"
        proxy:
          protect: false
          required_status_checks:
            contexts:
            - "ci/circleci: build"
          branches:
            <<: *blocked_branches
            endpoints-v1.1.x: *blocking_merge
            endpoints-v1.2.x: *blocking_merge
            release-1.1:
              protect: true
              required_status_checks:
                contexts:
                - "merges-blocked-needs-admin"
            release-1.2:
              protect: true
              required_status_checks:
                contexts:
                - "merges-blocked-needs-admin"
            master:
              protect: true
            wasm:
              protect: true
        test-infra:
          protect: false
          branches:
            master:
              protect: true
    istio-releases:
      repos:
        pipeline:
          protect: false
          restrictions:
          branches:
            krishna-test:
              protect: true
            master:
              protect: true
            release-1.2:
              protect: true
            release-1.1:
              protect: true
            release-1.0:
              protect: true
    istio-ecosystem:
      repos:
        authservice:
          protect: false
          restrictions:
          branches:
            master:
              protect: true

tide:
  queries:
  - repos:
    - istio-releases/pipeline
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-ok-to-test
    - needs-rebase
  - repos:
    - istio/api
    - istio/test-infra
    - istio/istio
    - istio/proxy
    - istio-ecosystem/authservice
    labels:
    - lgtm
    - approved
    - "cla: yes"
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-ok-to-test
    - needs-rebase
  merge_method:
    istio/api: squash
    istio/istio: squash
    istio/proxy: squash
    istio/test-infra: squash
    istio-releases/pipeline: squash
    istio-ecosystem/authservice: squash
  target_url: https://prow.istio.io/tide

  context_options:
    from-branch-protection: true
    skip-unknown-contexts: true

presets:
- labels:
    preset-service-account: "true"
  env:
  - name: GOOGLE_APPLICATION_CREDENTIALS
    value: /etc/service-account/service-account.json
  - name: CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE
    value: /etc/service-account/service-account.json
  volumeMounts:
  - name: service
    mountPath: /etc/service-account
    readOnly: true
  volumes:
  - name: service
    secret:
      secretName: service-account
- labels:
    preset-prow-bazel: "true"
  volumeMounts:
  - name: cache-ssd
    mountPath: /home/prow/.cache
  volumes:
  - name: cache-ssd
    hostPath:
      path: /mnt/disks/ssd0/test-infra
- labels:
    preset-bazel: "true"
  volumeMounts:
  - name: cache-ssd
    mountPath: /home/bootstrap/.cache
  volumes:
  - name: cache-ssd
    hostPath:
      path: /mnt/disks/ssd0/proxy
- labels:
    preset-release-pipeline: "true"
  env:
  - name: DOCKER_CONFIG
    value: /etc/rel-pipeline-docker-config
  - name: GITHUB_TOKEN_FILE
    value: /etc/github/rel-pipeline-github
  - name: GOOGLE_APPLICATION_CREDENTIALS
    value: /etc/service-account/rel-pipeline-service-account.json
  volumeMounts:
  - name: rel-pipeline-docker-config
    mountPath: /etc/rel-pipeline-docker-config
    readOnly: true
  - name: rel-pipeline-github
    mountPath: /etc/github
    readOnly: true
  - name: rel-pipeline-service-account
    mountPath: /etc/service-account
    readOnly: true
  volumes:
  - name: rel-pipeline-service-account
    secret:
      secretName: rel-pipeline-service-account
  - name: rel-pipeline-github
    secret:
      secretName: rel-pipeline-github
  - name: rel-pipeline-docker-config
    secret:
      secretName: rel-pipeline-docker-config
