---
plank:
  job_url_template: 'https://k8s-gubernator.appspot.com/build/istio-prow/{{if eq .Spec.Type "presubmit"}}pull{{else if eq .Spec.Type "batch"}}pr-logs/pull{{else}}logs{{end}}{{if ne .Spec.Refs.Org ""}}{{if ne .Spec.Refs.Org "kubernetes"}}/{{.Spec.Refs.Org}}_{{.Spec.Refs.Repo}}{{else if ne .Spec.Refs.Repo "kubernetes"}}/{{.Spec.Refs.Repo}}{{end}}{{end}}{{if eq .Spec.Type "presubmit"}}/{{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}{{else if eq .Spec.Type "batch"}}/batch{{end}}/{{.Spec.Job}}/{{.Status.BuildID}}/'

triggers:
- repos:
  - istio/istio
  - istio/test-infra
  - istio/pilot
  trusted_org: istio

presubmits:
  # PR job triggering definitions.
  # Keys: Full repo name: "org/repo".
  # Values: List of jobs to run when events occur in the repo.
  #   name:          Job name.
  #   trigger:       Regexp commenters can say to trigger the job.
  #   always_run:    Whether to run for every PR. Default is false. If this is
  #                  set then your trigger needs to match "@k8s-bot test this".
  #   context:       GitHub status context.
  #   rerun_command: How should users trigger just this job, as a string, not a
  #                  regex. For example, if the trigger regex is "(e2e )?test",
  #                  then a rerun command might be "e2e test".
  #   skip_report:   If true, then do not set status or comment on GitHub.
  #   spec:          If this exists then run a kubernetes pod with this spec.
  #                  Otherwise, run a Jenkins job.

  istio/istio:
  - name: istio-presubmit
    context: prow/istio-presubmit.sh
    always_run: true
    rerun_command: "@istio-testing bazel test this"
    trigger: "((?m)^@istio-testing (bazel )?test this,?(\\s+|$)|(?m)^/test( all| bazel),?(\\s+|$))"
    branches:
    - master
    spec:
      containers:
      - image: gcr.io/istio-testing/prowbazel:0.1.5
        args:
        - "--pull=$(PULL_REFS)"
        - "--clean"
        # Bazel needs privileged mode in order to sandbox builds.
        securityContext:
          privileged: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/service-account/service-account.json
        volumeMounts:
        - name: service
          mountPath: /etc/service-account
          readOnly: true
        - name: e2e-testing-kubeconfig
          mountPath: /etc/e2e-testing-kubeconfig
          readOnly: true
        - name: cache-ssd
          mountPath: /home/bootstrap/.cache
        ports:
        - containerPort: 9999
          hostPort: 9998
      volumes:
      - name: service
        secret:
          secretName: service-account
      - name: e2e-testing-kubeconfig
        secret:
          secretName: e2e-testing-kubeconfig
      - name: cache-ssd
        hostPath:
          path: /mnt/disks/ssd0

  istio/pilot:
  - name: pilot-presubmit
    context: prow/pilot-presubmit.sh
    always_run: true
    rerun_command: "@istio-testing bazel test this"
    trigger: "((?m)^@istio-testing (bazel )?test this,?(\\s+|$)|(?m)^/test( all| bazel),?(\\s+|$))"
    branches:
    - master
    spec:
      containers:
      - image: gcr.io/istio-testing/prowbazel:0.1.5
        args:
        - "--pull=$(PULL_REFS)"
        - "--clean"
        # Bazel needs privileged mode in order to sandbox builds.
        securityContext:
          privileged: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/service-account/service-account.json
        volumeMounts:
        - name: service
          mountPath: /etc/service-account
          readOnly: true
        - name: e2e-testing-kubeconfig
          mountPath: /etc/e2e-testing-kubeconfig
          readOnly: true
        - name: pilot-codecov-token
          mountPath: /etc/codecov
          readOnly: true
        - name: cache-ssd
          mountPath: /home/bootstrap/.cache
        ports:
        - containerPort: 9999
          hostPort: 9998
      volumes:
      - name: service
        secret:
          secretName: service-account
      - name: e2e-testing-kubeconfig
        secret:
          secretName: e2e-testing-kubeconfig
      - name: pilot-codecov-token
        secret:
          secretName: pilot-codecov-token
      - name: cache-ssd
        hostPath:
          path: /mnt/disks/ssd0

  istio/test-infra:
  - name: test-infra-presubmit
    context: prow/test-infra-presubmit.sh
    always_run: true
    rerun_command: "@istio-testing bazel test this"
    trigger: "((?m)^@istio-testing (bazel )?test this,?(\\s+|$)|(?m)^/test( all| bazel),?(\\s+|$))"
    branches:
    - master
    spec:
      containers:
      - image: gcr.io/istio-testing/prowbazel:0.1.5
        args:
        - "--pull=$(PULL_REFS)"
        - "--clean"
        # Bazel needs privileged mode in order to sandbox builds.
        securityContext:
          privileged: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/service-account/service-account.json
        volumeMounts:
        - name: service
          mountPath: /etc/service-account
          readOnly: true
        - name: cache-ssd
          mountPath: /home/bootstrap/.cache
        ports:
        - containerPort: 9999
          hostPort: 9998
      volumes:
      - name: service
        secret:
          secretName: service-account
      - name: cache-ssd
        hostPath:
          path: /mnt/disks/ssd0
