---
plank:
  job_url_template: 'https://k8s-gubernator.appspot.com/build/istio-prow/{{if eq .Spec.Type "presubmit"}}pull/{{.Spec.Refs.Org}}_{{.Spec.Refs.Repo}}/{{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}{{else}}.{{end}}/{{.Spec.Job}}/{{.Status.BuildID}}/'
  job_url_prefix: https://k8s-gubernator.appspot.com/build/
  pod_pending_timeout: 60m
  default_decoration_config:
    timeout: 7200000000000 # 2h
    grace_period: 15000000000 # 15s
    utility_images:
      clonerefs: "registry.svc.ci.openshift.org/ci/clonerefs:latest"
      initupload: "registry.svc.ci.openshift.org/ci/initupload:latest"
      entrypoint: "registry.svc.ci.openshift.org/ci/entrypoint:latest"
      sidecar: "registry.svc.ci.openshift.org/ci/sidecar:latest"
    gcs_configuration:
      bucket: "istio-prow"
      path_strategy: "explicit"
    gcs_credentials_secret: "service-account"

sinker:
  resync_period: 1h
  max_prowjob_age: 168h
  max_pod_age: 12h

deck:
  tide_update_period: 1s

prowjob_namespace: default
pod_namespace: test-pods

blocked_branches: &blocked_branches
  release-0.1: &blocking_merge
    required_status_checks:
      contexts:
      - "merges-blocked-needs-admin"
    protect: true
  release-0.2:
    <<: *blocking_merge
  release-0.3:
    <<: *blocking_merge
  release-0.3.0:
    <<: *blocking_merge
  release-0.4:
    <<: *blocking_merge
  release-0.4.0:
    <<: *blocking_merge
  release-0.5:
    <<: *blocking_merge
  release-0.6:
    <<: *blocking_merge
  release-0.7:
    <<: *blocking_merge
  release-0.8:
    <<: *blocking_merge
  release-1.0:
    <<: *blocking_merge
  release-1.0.0-snapshot.0:
    <<: *blocking_merge

branch-protection:
  allow_disabled_policies: true
  orgs:
    istio:
      required_status_checks:
        contexts:
        - cla/google
      required_pull_request_reviews:
        required_approving_review_count: 1
      restrictions:
        teams:
        - repo-admins
      repos:
        api:
          protect: false
          branches:
            <<: *blocked_branches
            master:
              protect: true
        istio:
          protect: false
          required_status_checks:
            contexts:
            - "ci/circleci: build"
            - "ci/circleci: e2e-simple"
            # Making lint not required until it is fixed.
            # - "ci/circleci: lint"
            - "ci/circleci: test"
          branches:
            <<: *blocked_branches
            collab-gcp-identity:
              protect: true
              restrictions:
                teams:
                - istio-hackers
            release-0.8:
              protect: true
              required_status_checks:
                contexts:
                - "ci/circleci: dependencies"
                - "ci/circleci: e2e-pilot"
                - "ci/circleci: e2e-pilot-noauth-v1alpha3-v2"
            master:
              protect: true
              required_status_checks:
                contexts:
                - "ci/circleci: shellcheck"
                - "ci/circleci: e2e-pilot-auth-v1alpha3-v2"
                - "ci/circleci: e2e-pilot-noauth-v1alpha3-v2"
                - "ci/circleci: e2e-mixer-noauth-v1alpha3-v2"
                - "ci/circleci: e2e-pilot-cloudfoundry-v1alpha3-v2"

        istio.github.io:
          protect: false
          required_status_checks:
            contexts:
            - ci/circleci
            - deploy/netlify
          branches:
            release-0.1:
              protect: true
            release-0.2:
              protect: true
            release-0.3:
              protect: true
            release-0.4:
              protect: true
            release-0.5:
              protect: true
            release-0.6:
              protect: true
            release-0.7:
              protect: true
            release-0.8:
              protect: true
            release-1.0:
              protect: true
            master:
              protect: true
        proxy:
          protect: false
          required_status_checks:
            contexts:
            - "ci/circleci: build"
          branches:
            <<: *blocked_branches
            endpoints-v1.1.x: *blocking_merge
            endpoints-v1.2.x: *blocking_merge
            master:
              protect: true
        test-infra:
          protect: false
          branches:
            master:
              protect: true
    istio-releases:
      repos:
        daily-release:
          protect: false
          restrictions:
          branches:
            release-0.8:
              protect: true
            release-1.0:
              protect: true
            release-1.0.0-snapshot.0:
              protect: true
            collab-gcp-identity:
              protect: true
            master:
              protect: true

tide:
  queries:
  - repos:
    - istio-releases/daily-release
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-ok-to-test
    - needs-rebase
  - repos:
    - istio/api
    - istio/test-infra
    - istio/istio
    - istio/proxy
    labels:
    - lgtm
    - approved
    - "cla: yes"
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-ok-to-test
    - needs-rebase
  - repos:
    - istio/istio.github.io
    labels:
    - lgtm
    - approved
    - "cla: yes"
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-rebase
  - repos:
    - istio-releases/daily-release
    labels:
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-rebase
  merge_method:
    istio/api: squash
    istio/istio.github.io: squash
    istio/istio: squash
    istio/proxy: squash
    istio/test-infra: squash
    istio-releases/daily-release: squash
  target_url: https://prow.istio.io/tide

  context_options:
    from-branch-protection: true
    skip-unknown-contexts: true

presets:
- labels:
    preset-service-account: "true"
  env:
  - name: GOOGLE_APPLICATION_CREDENTIALS
    value: /etc/service-account/service-account.json
  - name: CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE
    value: /etc/service-account/service-account.json
  volumeMounts:
  - name: service
    mountPath: /etc/service-account
    readOnly: true
  volumes:
  - name: service
    secret:
      secretName: service-account
- labels:
    preset-prow-bazel: "true"
  volumeMounts:
  - name: cache-ssd
    mountPath: /home/prow/.cache
  volumes:
  - name: cache-ssd
    hostPath:
      path: /mnt/disks/ssd0/test-infra
- labels:
    preset-bazel: "true"
  volumeMounts:
  - name: cache-ssd
    mountPath: /home/bootstrap/.cache
  volumes:
  - name: cache-ssd
    hostPath:
      path: /mnt/disks/ssd0/proxy
