---
plank:
  job_url_template: 'https://prow.istio.io/view/gcs/istio-prow{{if eq .Spec.Type "presubmit"}}/pr-logs/pull/{{.Spec.Refs.Org}}_{{.Spec.Refs.Repo}}/{{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}{{else if .Spec.Type "batch"}}/pr-logs/pull/batch{{else}}/logs{{end}}/{{.Spec.Job}}/{{.Status.BuildID}}'
  job_url_prefix: https://prow.istio.io/view/gcs/
  pod_pending_timeout: 60m
  default_decoration_config:
    # TODO(fejta): use 2h, 15s instead
    timeout: 7200000000000 # 2h
    grace_period: 15000000000 # 15s
    utility_images:
      clonerefs: "gcr.io/k8s-prow/clonerefs:v20190715-1dacc7e01"
      initupload: "gcr.io/k8s-prow/initupload:v20190715-1dacc7e01"
      entrypoint: "gcr.io/k8s-prow/entrypoint:v20190715-1dacc7e01"
      sidecar: "gcr.io/k8s-prow/sidecar:v20190715-1dacc7e01"
    gcs_configuration:
      bucket: "istio-prow"
      path_strategy: "explicit"
    gcs_credentials_secret: "service-account"

sinker:
  resync_period: 1h
  max_prowjob_age: 168h
  max_pod_age: 6h

deck:
  spyglass:
    size_limit: 500000000 # 500MB
    gcs_browser_prefix: https://gcsweb.k8s.io/gcs/
    testgrid_config: gs://k8s-testgrid/config
    testgrid_root: https://testgrid.k8s.io/
    viewers:
      "started.json|finished.json":
      - "metadata"
      "build-log.txt":
      - "buildlog"
      "artifacts/junit.*\\.xml":
      - "junit"
      "artifacts/filtered.cov":
      - "coverage"
    announcement: "This page -- spyglass -- is the default viewer for prow.{{if .ArtifactPath}} For now, the deprecated gubernator page spyglass replaces <a href='https://gubernator.k8s.io/build/{{.ArtifactPath}}'>remains available</a>.{{end}}"

  tide_update_period: 1s

prowjob_namespace: default
pod_namespace: test-pods

# Report job status for presubmit and postsubmit
github_reporter:
  job_types_to_report:
  - presubmit
  - postsubmit

blocked_branches: &blocked_branches
  release-*: &blocking_merge
    required_status_checks:
      contexts:
      - "merges-blocked-needs-admin"
    protect: true

branch-protection:
  allow_disabled_policies: true
  orgs:
    istio:
      required_status_checks:
        contexts:
        - cla/google
      required_pull_request_reviews:
        required_approving_review_count: 1
      restrictions:
      repos:
        api:
          protect: false
          branches:
            <<: *blocked_branches
            master:
              protect: true
        istio.io:
          protect: false
          branches:
            <<: *blocked_branches
            master:
              protect: true
        operator:
          protect: false
          branches:
            <<: *blocked_branches
            master:
              protect: true
        cni:
          protect: false
          branches:
            <<: *blocked_branches
            master:
              protect: true
        installer:
          protect: false
          branches:
            <<: *blocked_branches
            master:
              protect: true
              required_status_checks:
                contexts:
                # Keep in sync with .mergify.yml required
                - "ci/circleci: build"
                - "ci/circleci: install-demo"
                - "ci/circleci: install-minikube"
                - "ci/circleci: integration-old-kind"
                - "ci/circleci: integration-presubmit-isolated-namespaces-kind"
                - "ci/circleci: integration-presubmit-one-namespace-kind"
                - "ci/circleci: noauth"
        pkg:
          protect: false
          branches:
            <<: *blocked_branches
            master:
              protect: true
        common-files:
          protect: false
          branches:
            <<: *blocked_branches
            master:
              protect: true
        istio:
          protect: false
          branches:
            <<: *blocked_branches
            collab-galley:
              protect: true
              restrictions:
                teams:
                - istio-hackers
            collab-gce-identity:
              protect: true
            prow-staging:
              protect: true
            release-1.1:
              protect: true
              required_status_checks:
                contexts:
                - "ci/circleci: codecov"
                - "ci/circleci: shellcheck"
                - "ci/circleci: lint"
                - "ci/circleci: test"
                - "ci/circleci: build"
                - "ci/circleci: e2e-pilot-cloudfoundry-v1alpha3-v2"
                - "merges-blocked-needs-admin"
            release-1.2:
              protect: true
              required_status_checks:
                contexts:
                - "ci/circleci: codecov"
                - "ci/circleci: shellcheck"
                - "ci/circleci: lint"
                - "ci/circleci: test"
                - "ci/circleci: build"
                - "ci/circleci: e2e-pilot-cloudfoundry-v1alpha3-v2"
                - "merges-blocked-needs-admin"
            master:
              protect: true
        proxy:
          protect: false
          required_status_checks:
            contexts:
            - "ci/circleci: build"
          branches:
            <<: *blocked_branches
            endpoints-v1.1.x: *blocking_merge
            endpoints-v1.2.x: *blocking_merge
            release-1.1:
              protect: true
              required_status_checks:
                contexts:
                - "merges-blocked-needs-admin"
            release-1.2:
              protect: true
              required_status_checks:
                contexts:
                - "merges-blocked-needs-admin"
            master:
              protect: true
            wasm:
              protect: true
        test-infra:
          protect: false
          branches:
            master:
              protect: true
    istio-releases:
      repos:
        pipeline:
          protect: false
          restrictions:
          branches:
            krishna-test:
              protect: true
            master:
              protect: true
            release-1.2:
              protect: true
            release-1.1:
              protect: true
            release-1.0:
              protect: true
    istio-ecosystem:
      repos:
        authservice:
          protect: false
          restrictions:
          branches:
            master:
              protect: true

tide:
  queries:
  - repos:
    - istio-releases/pipeline
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-ok-to-test
    - needs-rebase
  - repos:
    - istio/test-infra
    - istio/istio
    - istio/proxy
    - istio-ecosystem/authservice
    labels:
    - lgtm
    - approved
    - "cla: yes"
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-rebase
  merge_method:
    istio/istio: squash
    istio/proxy: squash
    istio/test-infra: squash
    istio-releases/pipeline: squash
    istio-ecosystem/authservice: squash
  target_url: https://prow.istio.io/tide

  context_options:
    from-branch-protection: true
    skip-unknown-contexts: true

presets:
- labels:
    preset-service-account: "true"
  env:
  - name: GOOGLE_APPLICATION_CREDENTIALS
    value: /etc/service-account/service-account.json
  - name: CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE
    value: /etc/service-account/service-account.json
  volumeMounts:
  - name: service
    mountPath: /etc/service-account
    readOnly: true
  volumes:
  - name: service
    secret:
      secretName: service-account
- labels:
    preset-bazel: "true"
  volumeMounts:
  - name: cache-ssd
    mountPath: /home/bootstrap/.cache
  volumes:
  - name: cache-ssd
    hostPath:
      path: /mnt/disks/ssd0/proxy
- labels:
    preset-release-pipeline: "true"
  env:
  - name: DOCKER_CONFIG
    value: /etc/rel-pipeline-docker-config
  - name: GITHUB_TOKEN_FILE
    value: /etc/github/rel-pipeline-github
  - name: GOOGLE_APPLICATION_CREDENTIALS
    value: /etc/service-account/rel-pipeline-service-account.json
  volumeMounts:
  - name: rel-pipeline-docker-config
    mountPath: /etc/rel-pipeline-docker-config
    readOnly: true
  - name: rel-pipeline-github
    mountPath: /etc/github
    readOnly: true
  - name: rel-pipeline-service-account
    mountPath: /etc/service-account
    readOnly: true
  volumes:
  - name: rel-pipeline-service-account
    secret:
      secretName: rel-pipeline-service-account
  - name: rel-pipeline-github
    secret:
      secretName: rel-pipeline-github
  - name: rel-pipeline-docker-config
    secret:
      secretName: rel-pipeline-docker-config
- labels:
    preset-release-build-test: "true"
  env:
  - name: DOCKER_CONFIG
    value: /etc/rel-pipeline-docker-config
  - name: GITHUB_TOKEN_FILE
    value: /etc/github/rel-pipeline-github
  - name: GOOGLE_APPLICATION_CREDENTIALS
    value: /etc/service-account/service-account.json
  - name: CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE
    value: /etc/service-account/service-account.json
  volumeMounts:
  - name: rel-pipeline-docker-config
    mountPath: /etc/rel-pipeline-docker-config
    readOnly: true
  - name: rel-pipeline-github
    mountPath: /etc/github
    readOnly: true
  - name: service
    mountPath: /etc/service-account
    readOnly: true
  volumes:
  - name: service
    secret:
      secretName: service-account
  - name: rel-pipeline-docker-config
    secret:
      secretName: rel-pipeline-docker-config
  - name: rel-pipeline-github
    secret:
      secretName: rel-pipeline-github
