# Plugin repository whitelist.
# Keys: Full repo name: "org/repo".
# Values: List of plugins to run against the repo.
---
triggers:
- repos:
  - istio
  - istio-releases/pipeline
  trusted_org: istio
- repos:
  - istio-ecosystem/authservice

config_updater:
  maps:
    prow/config.yaml:
      name: config
    prow/plugins.yaml:
      name: plugins
    boskos/resources.yaml:
      name: boskos-config
      namespace: boskos
    boskos/configs.yaml:
      name: mason-config
      namespace: boskos
    prow/cluster/jobs/**/*.yaml:
      name: job-config

slack:
  mergewarnings:
  - repos:
    - istio/test-infra
    channels:
    - test-and-release
    whitelist:
    - istio-testing

lgtm:
- repos:
  - istio
  review_acts_as_lgtm: true
- repos:
  - istio/istio
  - istio/test-infra
  - istio/proxy
  - istio-releases/pipeline
  review_acts_as_lgtm: true
  trusted_team_for_sticky_lgtm: "Istio Hackers"
- repos:
  - istio-ecosystem/authservice
  review_acts_as_lgtm: true

approve:
- repos:
  - istio/istio
  - istio/test-infra
  - istio/proxy
  - istio-releases/pipeline
  implicit_self_approve: true
- repos:
  - istio-ecosystem/authservice
  implicit_self_approve: true

plugins:
  istio: # TODO(fejta): make this the same for other orgs
  - assign # manage assignees/reviewers via email
  # blunderbuss TODO(fejta): teach blunderbuss to read CODEOWNERS, or is this just unnecssary?
  - config-updater # auto-update requested configmaps
  - golint # inline golint auto-review
  - hold # manual hold command
  - lifecycle # close or mark issues as stale via email
  - override # admins can force a context to pass
  - size # search for PRs with a small label to review quickly
  - skip # cleans up non-blocking statuses from old commits
  - slackevents # post requested messages to slack, if any
  - trigger # run tests
  - verify-owners # ensures any OWNERS changes are valid
  - wip # wip label based on title/draft status

  istio/istio:
  - approve # TODO(fejta): consider using tide + review:approved and dropping this everywhere
  - blunderbuss
  - lgtm # TODO(fejta): consider using tide + review:approved instead

  istio/proxy:
  - approve
  - blunderbuss
  - lgtm

  istio/test-infra:
  - approve
  - blunderbuss
  - lgtm

  istio-releases/pipeline:
  - lifecycle
  - trigger
  - hold

  istio-ecosystem/authservice:
  - approve
  - assign
  - blunderbuss
  - golint
  - help
  - hold
  - lgtm
  - lifecycle
  - slackevents
  - trigger
  - verify-owners
  - wip

external_plugins:
  istio:
  - name: needs-rebase
    events:
      - pull_request
  istio-releases/pipeline:
  - name: needs-rebase
    events:
      - pull_request
  istio-ecosystem/authservice:
  - name: needs-rebase
    events:
      - pull_request
