# Plugin repository whitelist.
# Keys: Full repo name: "org/repo".
# Values: List of plugins to run against the repo.
---
triggers:
- repos:
  - istio/api
  - istio/auth
  - istio/broker
  - istio/istio
  - istio/mixer
  - istio/pilot
  - istio/test-infra
  trusted_org: istio

plugins:
  istio/api:
  - assign
  - trigger
  - close

  istio/auth:
  - assign
  - trigger
  - close
  - release-note
  - reopen
  - lgtm

  istio/broker:
  - assign
  - trigger
  - close

  istio/istio:
  - assign
  - trigger
  - release-note
  - close
  - reopen
  - lgtm

  istio/mixer:
  - assign
  - trigger
  - release-note
  - close
  - reopen
  - lgtm

  istio/pilot:
  - assign
  - trigger
  - release-note
  - close
  - reopen
  - lgtm

  istio/test-infra:
  - assign
  - trigger
  - config-updater
  - release-note
  - close
  - reopen
  - lgtm
  - hold
  - yuks
