# Plugin repository whitelist.
# Keys: Full repo name: "org/repo".
# Values: List of plugins to run against the repo.
---
triggers:
- repos:
  - istio/api
  - sebastienvas/core
  - istio/istio
  - istio/test-infra
  - istio/mixerclient
  - istio/proxy
  - istio-releases/daily-release
  trusted_org: istio

config_updater:
  maps:
    prow/config.yaml: config
    prow/plugins.yaml: plugins

plugins:
  istio/api:
  - assign
  - close
  - trigger

  sebastienvas/core:
  - assign
  - close
  - hold
  - lgtm
  - release-note
  - reopen
  - trigger

  istio/istio:
  - approve
  - assign
  - close
  - hold
  - lgtm
  - reopen
  - trigger

  istio/mixerclient:
  - approve
  - assign
  - close
  - hold
  - lgtm
  - reopen
  - trigger

  istio/proxy:
  - approve
  - assign
  - close
  - hold
  - lgtm
  - reopen
  - trigger

  istio/test-infra:
  - approve
  - assign
  - close
  - config-updater
  - hold
  - lgtm
  - reopen
  - trigger
  - yuks

  istio-releases/daily-release:
  - trigger
