# Plugin repository whitelist.
# Keys: Full repo name: "org/repo".
# Values: List of plugins to run against the repo.
---
triggers:
- repos:
  - istio/api
  - sebastienvas/core
  - istio/istio
  - istio/istio.github.io
  - istio/test-infra
  - istio/proxy
  - istio-releases/daily-release
  trusted_org: istio

config_updater:
  maps:
    prow/config.yaml:
      name: config
    prow/plugins.yaml:
      name: plugins
    boskos/resources.yaml:
      name: boskos-config
      namespace: boskos
    boskos/configs.yaml:
      name: mason-config
      namespace: boskos
    prow/cluster/jobs/**/*.yaml:
      name: job-config

slack:
  mergewarnings:
  - repos:
    - istio/istio
    - istio/api
    - istio/proxy
    - istio/istio.github.io
    channels:
    - oncall
    whitelist:
    - istio-testing
  - repos:
    - istio/test-infra
    channels:
    - test-and-release
    whitelist:
    - istio-testing

approve:
- repos:
  - istio/api
  - istio/istio
  - istio/istio.github.io
  - istio/test-infra
  - istio/proxy
  - istio-releases/daily-release
  implicit_self_approve: false
  lgtm_acts_as_approve: true

plugins:
  istio:
  - approve
  - assign
  - blunderbuss
  - golint
  - help
  - hold
  - lgtm
  - lifecycle
  - trigger
  - wip

  sebastienvas/core:
  - assign
  - hold
  - lgtm
  - lifecycle
  - trigger

  istio/test-infra:
  - config-updater
  - shrug
  - skip
  - slackevents
  - yuks

  istio-releases/daily-release:
  - lifecycle
  - trigger

external_plugins:
  istio/istio:
  - name: needs-rebase
    events:
      - pull_request
  istio/istio.github.io:
  - name: needs-rebase
    events:
      - pull_request
  istio/proxy:
  - name: needs-rebase
    events:
      - pull_request
  istio/test-infra:
  - name: needs-rebase
    events:
      - pull_request
