# Plugin repository whitelist.
# Keys: Full repo name: "org/repo".
# Values: List of plugins to run against the repo.
---
triggers:
- repos:
  - istio/api
  - sebastienvas/core
  - istio/istio
  - istio/istio.github.io
  - istio/test-infra
  - istio/mixerclient
  - istio/proxy
  - istio-releases/daily-release
  trusted_org: istio

config_updater:
  maps:
    prow/config.yaml:
      name: config
    prow/plugins.yaml:
      name: plugins
    boskos/resources.yaml:
      name: boskos-config
      namespace: boskos
    boskos/configs.yaml:
      name: mason-config
      namespace: boskos

plugins:
  istio/api:
  - assign
  - blunderbuss
  - close
  - trigger

  sebastienvas/core:
  - assign
  - close
  - hold
  - lgtm
  - release-note
  - reopen
  - trigger

  istio/istio:
  - approve
  - assign
  - blunderbuss
  - close
  - hold
  - lgtm
  - reopen
  - trigger

  istio/istio.github.io:
  - approve
  - assign
  - blunderbuss
  - close
  - hold
  - lgtm
  - reopen
  - trigger

  istio/proxy:
  - approve
  - assign
  - blunderbuss
  - close
  - hold
  - lgtm
  - reopen
  - trigger

  istio/test-infra:
  - approve
  - assign
  - blunderbuss
  - close
  - config-updater
  - hold
  - lgtm
  - reopen
  - trigger
  - yuks

  istio-releases/daily-release:
  - trigger

external_plugins:
  istio/istio:
  - name: needs-rebase
    events:
      - pull_request
  istio/istio.github.io:
  - name: needs-rebase
    events:
      - pull_request
  istio/proxy:
  - name: needs-rebase
    events:
      - pull_request
  istio/test-infra:
  - name: needs-rebase
    events:
      - pull_request
