# Plugin repository whitelist.
# Keys: Full repo name: "org/repo".
# Values: List of plugins to run against the repo.
---
triggers:
- repos:
  - istio/api
  - istio/common-files
  - istio/cni
  - istio/installer
  - istio/istio
  - istio/istio.io
  - istio/operator
  - istio/pkg
  - istio/proxy
  - istio/test-infra
  - istio-releases/pipeline
  - sebastienvas/core
  trusted_org: istio
- repos:
  - istio-ecosystem/authservice

config_updater:
  maps:
    prow/config.yaml:
      name: config
    prow/plugins.yaml:
      name: plugins
    boskos/resources.yaml:
      name: boskos-config
      namespace: boskos
    boskos/configs.yaml:
      name: mason-config
      namespace: boskos
    prow/cluster/jobs/**/*.yaml:
      name: job-config
    label_sync/labels.yaml:
      name: label-config
      namespace: test-pods

slack:
  mergewarnings:
  - repos:
    - istio/test-infra
    channels:
    - test-and-release
    whitelist:
    - istio-testing

lgtm:
- repos:
  - istio
  review_acts_as_lgtm: true
- repos:
  - istio/istio
  - istio/test-infra
  - istio/proxy
  - istio-releases/pipeline
  lgtm_acts_as_approve: true # TODO(fejta): delete https://github.com/istio/test-infra/issues/1433
  review_acts_as_lgtm: true
  trusted_team_for_sticky_lgtm: "Istio Hackers"
- repos:
  - istio-ecosystem/authservice
  lgtm_acts_as_approve: true # TODO(fejta): delete https://github.com/istio/test-infra/issues/1433
  review_acts_as_lgtm: true

approve:
- repos:
  - istio/istio
  - istio/test-infra
  - istio/proxy
  - istio-releases/pipeline
  implicit_self_approve: true
- repos:
  - istio-ecosystem/authservice
  implicit_self_approve: true

plugins:
  istio/istio:
  - approve
  - assign
  - blunderbuss
  - golint
  - help
  - hold
  - lgtm
  - lifecycle
  - slackevents
  - trigger
  - verify-owners
  - wip

  istio/api:
  - approve
  - assign
  - blunderbuss
  - golint
  - help
  - hold
  - lgtm
  - lifecycle
  - slackevents
  - trigger
  - verify-owners
  - wip

  istio/installer:
  - trigger

  istio/operator:
  - assign
  - hold
  - slackevents
  - trigger
  - wip

  istio/proxy:
  - approve
  - assign
  - blunderbuss
  - golint
  - help
  - hold
  - lgtm
  - lifecycle
  - slackevents
  - trigger
  - verify-owners
  - wip

  sebastienvas/core:
  - assign
  - hold
  - lgtm
  - lifecycle
  - trigger

  istio/test-infra:
  - approve
  - assign
  - blunderbuss
  - config-updater
  - golint
  - help
  - hold
  - lgtm
  - lifecycle
  - shrug
  - skip
  - slackevents
  - trigger
  - verify-owners
  - wip
  - yuks

  istio-releases/pipeline:
  - lifecycle
  - trigger
  - hold

  istio-ecosystem/authservice:
  - approve
  - assign
  - blunderbuss
  - golint
  - help
  - hold
  - lgtm
  - lifecycle
  - slackevents
  - trigger
  - verify-owners
  - wip

external_plugins:
  istio/istio:
  - name: needs-rebase
    events:
      - pull_request
  istio/proxy:
  - name: needs-rebase
    events:
      - pull_request
  istio/test-infra:
  - name: needs-rebase
    events:
      - pull_request
  istio-releases/pipeline:
  - name: needs-rebase
    events:
      - pull_request
  istio-ecosystem/authservice:
  - name: needs-rebase
    events:
      - pull_request
