# Plugin repository whitelist.
# Keys: Full repo name: "org/repo".
# Values: List of plugins to run against the repo.
---
triggers:
- repos:
  - dex80526/private_istio
  - dex80526/test-infra
  - dex80526/aspenmesh_private_istio

config_updater:
  maps:
    prow/config.yaml:
      name: config
    prow/plugins.yaml:
      name: plugins
    prow/cluster/jobs/**/*.yaml:
      name: job-config

slack:
  mergewarnings:
  - repos:
    - dex80526/test-infra
    - dex80526/private_istio
    - dex80526/aspenmesh_private_istio
    channels:
    - am-prow
    whitelist:
    - istio-testing

lgtm:
- repos:
  - dex80526/test-infra
  - dex80526/private_istio
  - dex80526/aspenmesh_private_istio
  review_acts_as_lgtm: true
- repos:
  - dex80526/test-infra
  - dex80526/private_istio
  - dex80526/aspenmesh_private_istio
  review_acts_as_lgtm: true
  trusted_team_for_sticky_lgtm: "Istio Hackers"

approve:
- repos:
  - dex80526/test-infra
  implicit_self_approve: true

plugins:
  dex80526/private_istio:
  - size
  - trigger
  - wip

  dex80526/aspenmesh_private_istio:
  - size
  - trigger
  - wip

  dex80526/test-infra:
  - size
  - trigger
  - wip
  - config-updater

  istio-ecosystem:
  - size
  - trigger
  - wip

  istio/test-infra:
  - assign
  - config-updater
  - golint
  - hold
  - lifecycle
  - skip
  - slackevents

  istio-releases/pipeline:
  - lifecycle
  - hold

  istio-ecosystem/authservice:
  - approve
  - assign
  - blunderbuss
  - golint
  - help
  - hold
  - lgtm
  - lifecycle
  - slackevents
  - verify-owners

external_plugins:
  dex80526/test-infra:
  - name: needs-rebase
    events:
    - pull_request
  dex80526/private_istio:
  - name: needs-rebase
    events:
    - pull_request    
  dex80526/aspenmesh_private_istio:
  - name: needs-rebase
    events:
    - pull_request          
  istio:
  - name: needs-rebase
    events:
    - pull_request
  - name: cherrypicker
    events:
      - issue_comment
      - pull_request
  istio-releases/pipeline:
  - name: needs-rebase
    events:
    - pull_request
  istio-ecosystem/authservice:
  - name: needs-rebase
    events:
    - pull_request
