# Plugin repository whitelist.
# Keys: Full repo name: "org/repo".
# Values: List of plugins to run against the repo.
---
triggers:
- repos:
  - istio/api
  - sebastienvas/core
  - istio/istio
  - istio/test-infra
  - istio/proxy
  - istio-releases/pipeline
  trusted_org: istio
- repos:
  - istio-ecosystem/authservice

config_updater:
  maps:
    prow/config.yaml:
      name: config
    prow/plugins.yaml:
      name: plugins
    boskos/resources.yaml:
      name: boskos-config
      namespace: boskos
    boskos/configs.yaml:
      name: mason-config
      namespace: boskos
    prow/cluster/jobs/**/*.yaml:
      name: job-config

slack:
  mergewarnings:
  - repos:
    - istio/test-infra
    channels:
    - test-and-release
    whitelist:
    - istio-testing

lgtm:
- repos:
  - istio/api
  - istio/istio
  - istio/test-infra
  - istio/proxy
  - istio-releases/pipeline
  trusted_team_for_sticky_lgtm: "Istio Hackers"
- repos:
  - istio-ecosystem/authservice

approve:
- repos:
  - istio/api
  - istio/istio
  - istio/test-infra
  - istio/proxy
  - istio-releases/pipeline
  implicit_self_approve: true
  lgtm_acts_as_approve: true
- repos:
  - istio-ecosystem/authservice
  implicit_self_approve: true
  lgtm_acts_as_approve: true

plugins:
  istio/istio:
  - approve
  - assign
  - blunderbuss
  - golint
  - help
  - hold
  - lgtm
  - lifecycle
  - slackevents
  - trigger
  - wip

  istio/api:
  - approve
  - assign
  - blunderbuss
  - golint
  - help
  - hold
  - lgtm
  - lifecycle
  - slackevents
  - trigger
  - wip

  istio/proxy:
  - approve
  - assign
  - blunderbuss
  - golint
  - help
  - hold
  - lgtm
  - lifecycle
  - slackevents
  - trigger
  - wip

  sebastienvas/core:
  - assign
  - hold
  - lgtm
  - lifecycle
  - trigger

  istio/test-infra:
  - config-updater
  - shrug
  - skip
  - yuks
  - approve
  - assign
  - blunderbuss
  - golint
  - help
  - hold
  - lgtm
  - lifecycle
  - slackevents
  - trigger
  - wip

  istio-releases/pipeline:
  - lifecycle
  - trigger

  istio-ecosystem/authservice:
  - approve
  - assign
  - blunderbuss
  - golint
  - help
  - hold
  - lgtm
  - lifecycle
  - slackevents
  - trigger
  - wip

external_plugins:
  istio/istio:
  - name: needs-rebase
    events:
      - pull_request
  istio/proxy:
  - name: needs-rebase
    events:
      - pull_request
  istio/test-infra:
  - name: needs-rebase
    events:
      - pull_request
  istio/pipeline:
  - name: needs-rebase
    events:
      - pull_request
  istio-ecosystem/authservice:
  - name: needs-rebase
    events:
      - pull_request