kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: oncall-alert
spec:
  replicas: 1
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
  template:
    metadata:
      labels:
        istio: oncall-alert
    spec:
      containers:
      - name: oncall-alert
        image: gcr.io/istio-testing/oncall_alert:0.0.2
        imagePullPolicy: Always 
